apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${K8S_DEPLOYMENT_NAME}
  labels:
    app: ${K8S_DEPLOYMENT_NAME}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ${K8S_DEPLOYMENT_NAME}
  template:
    metadata:
      labels:
        app: ${K8S_DEPLOYMENT_NAME}
    spec:
      containers:
        - name: ${K8S_DEPLOYMENT_NAME}
          image: ${DOCKER_IMAGE}  # This will be replaced dynamically
          ports:
            - containerPort: 8080
